SystemOrganization addCategory: #'GToolkit-Examples'!
SystemOrganization addCategory: 'GToolkit-Examples-Core'!
SystemOrganization addCategory: 'GToolkit-Examples-Exceptions'!
SystemOrganization addCategory: 'GToolkit-Examples-Organization'!
SystemOrganization addCategory: 'GToolkit-Examples-Runtime'!
SystemOrganization addCategory: 'GToolkit-Examples-Subjects'!
SystemOrganization addCategory: 'GToolkit-Examples-Testing'!
