"
I store metadata for this package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser
"
Class {
	#name : #ManifestGToolkitExamplesUI,
	#superclass : #PackageManifest,
	#category : 'GToolkit-Examples-UI'
}

{ #category : #'meta-data' }
ManifestGToolkitExamplesUI class >> description [ ^ 'I provide a set of basic tools extensions for the Inspector, Spotter and Nautilus for working with examples.'
]
