Extension { #name : #Float }

{ #category : #'*GToolkit-Examples-Extensions' }
Float class >> gtExampleE [
	<gtExample>
	<label: 'Float with e'>
	
	^ 42.42e42
]

{ #category : #'*GToolkit-Examples-Extensions' }
Float class >> gtExampleNegativeE [
	<gtExample>
	<label: 'Float with negative e'>
	
	^ 42.42e-42
]

{ #category : #'*GToolkit-Examples-Extensions' }
Float class >> gtExampleZero [
	<gtExample>
	<label: 'Zero'>
	
	^ 0.0
]
