Extension { #name : #ZnHeaders }

{ #category : #'*GToolkit-Examples-Extensions' }
ZnHeaders class >> gtExampleDefaultRequestHeaders [
	<gtExample>
	<label: 'Default request headers'>
	
	^ self defaultRequestHeaders
]

{ #category : #'*GToolkit-Examples-Extensions' }
ZnHeaders class >> gtExampleDefaultResponseHeaders [
	<gtExample>
	<label: 'Default response headers'>
	
	^ self defaultResponseHeaders
]
