Class {
	#name : #GtDummyExamplesWithInheritanceSubclassF,
	#superclass : #GtDummyExamplesWithInheritanceSubclassE,
	#category : #'GToolkit-Examples-Dummies-Data'
}

{ #category : #examples }
GtDummyExamplesWithInheritanceSubclassF class >> exampleA [
	^ 'aaa_no_example'
]

{ #category : #examples }
GtDummyExamplesWithInheritanceSubclassF class >> exampleH [
	^ 'hhh_no_example'
]

{ #category : #examples }
GtDummyExamplesWithInheritanceSubclassF >> exampleA [
	^ 'aa_no_example'
]
