"
I store metadata for this package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser
"
Class {
	#name : #ManifestGToolkitExamplesDummies,
	#superclass : #PackageManifest,
	#category : 'GToolkit-Examples-Dummies'
}

{ #category : #'meta-data' }
ManifestGToolkitExamplesDummies class >> description [ ^ 'I provide examples for testing the examples engine. The examples that I contain do not aim to test any domain object only exercise various features of the engine. That is why they are labeled "dummy".'
]
